### ISSUE TITLE
Question about the equations in the paper

### ISSUE THREAD

**Issue by emjay73** [POSTECH-CVLab/SCNeRF#15]
Q1
![image](https://user-images.githubusercontent.com/36818801/163548850-8a2bb720-cf25-4e2b-a2ac-3417d8bda9cc.png)
Is it true that each element of n is divided by c ? not f?

Also, what is the meaning of p' value?
undistorted pixel?

Q2 
![image](https://user-images.githubusercontent.com/36818801/163587846-444c39a4-4d4a-4ed4-b0fe-637eaf98935c.png)
In this equation, I'm not sure why $z_d$ is multiplied twice.

Q3
![image](https://user-images.githubusercontent.com/36818801/163596462-ee7b7eed-35b6-4f98-8ffe-87d6df29157e.png)
In this equation, why divide it by $r_{A,d} \cdot r_{A,d}$ instead of $||r_{A,d}||$ ?

Q4
![image](https://user-images.githubusercontent.com/36818801/163599477-41f49599-3308-4e10-a23d-2f38b83d1b59.png)
In this equation, round L in the last term should be round r?

**Comment by jeongyw12382** [comment]
Thanks for your questions. 
We'll double check your questions here and soon give you the reply.

**Comment by jeongyw12382** [comment]
An update for this issue. 
1. We have normalized the coordinate of each pixel to [-1, 1] when applying radial distortions. Using f instead of c could also enhance the camera model. However, we expect changing the radial parameters could somewhat show similar behaviors. This setups were fine for our experiments. (+p' is the pixel coordinate after distortions have been applied)
2, 3, 4. You are right. We will update the arXiv preprint soon. Fortunately, the pointed parts do not cause errors in our code or performance. Thanks for your suggestion.

**Comment by emjay73** [comment]
About Q1.
I thought the purpose of the eq5 is to convert pixel coordinates to normalized coordinate(z=1) as other distortion model does, but what you actually intended was to make pixel coordinates range from -1 to 1 right?
And if p' is distorted pixel coordinates, then the ray direction in eq 8 is a distorted ray direction? 
I expected p' to be undistorted pixel coordinates so it's a bit confusing.

About Q2,3,4
Thank you for your confirmation. You cleared things up.
