### ISSUE TITLE
Implementing SCNeRF on custom dataset

### ISSUE THREAD

**Issue by shreyk25** [POSTECH-CVLab/SCNeRF#19]
Hi @jeongyw12382 ,

I have a set of images. However, I am aware of the FOV and θ, Φ 3D angles for each image. 
Would it be possible for me train the NeRF model without COLMAP? 
Unfortunately, colmap doesn't work well on my dataset. I get an error saying:
`ERROR: the correct camera poses for current points cannot be accessed`

**Comment by jeongyw12382** [comment]
Hi. Sorry for being late. In my personal opinion, if you are aware of 3D angles then you could get the rotation matrix of camera. Unfortunately, if you were not aware of translation vectors, probably you should attempt to optimize the translation vectors only. (Not sure whether this method works well)

**Comment by shreyk25** [comment]
Thanks @jeongyw12382 ! I will try to extract that directly without using COLMAP.

However, do you think I could directly use SCNERF without giving any poses (random poses will be initialised)? 
I am aware of the custom branch that has been created. It has been created for the same reason right?

**Comment by jeongyw12382** [comment]
In my opinion, extending this work to non-normalized coordinate(ndc coordinate) can be future work since our experiments especially works well when coordinate normalization is feasible. The reason for making the custom branch is to extend the code to readily use on your custom dataset. Probably several techniques should be considered if you want to gain great quality. Please let me know if you had any issue regarding our implementation.
