### ISSUE TITLE
Does `--dataset_type custom` work for 360 scenes with photos only ?

### ISSUE THREAD

**Issue by vishnukool** [POSTECH-CVLab/SCNeRF#5]
Two questions, if you don't mind:

1. Does the code in "custom" branch with --dataset_type custom work for 360 degree scenes like the "tanks_and_temples" images ? Or is it only for forward facing scenes like LLFF fern dataset?
2. If it does work for 360 scenes, can you confirm that it doesn't need any COLMAP camera parameters, initialization, etc. ?

**Comment by jeongyw12382** [comment]
Before the main description, I should mention that the "custom" branch is one of the examples of the custom dataset. I made this branch because of the issue https://github.com/POSTECH-CVLab/SCNeRF/issues/3#issuecomment-952559113. Thus this is not fully verified. I strongly recommend double-checking the code before using it. 

First, the custom loader is designed to be similar to the "LLFF" dataset. Thus, you can feel free to use 360 scenes. However, the COLMAP process is required since we cannot get the camera pose without COLMAP.

In addition, if you ever want to use known camera parameters, instead of utilizing COLMAP, you should slightly modify the code.

**Comment by vishnukool** [comment]
Ah thanks for the clarification @jeongyw12382 
So basically for 360 scenes we still need COLMAP process? And there's no way around it ?

**Comment by vishnukool** [comment]
Secondly is there a better starting template than `main1_fern_ours.sh` for training on 360 scenes ?
Since I assume that config is for forward facing scenes.

**Comment by jeongyw12382** [comment]
@vishnukool 
Hmm... my future extension attempts to enable 360 scene calibration. 
However, I cannot ensure whether SCNeRF works perfectly fine for 360 scenes yet.

**Comment by vishnukool** [comment]
Thanks for the clarification @jeongyw12382 
I see that the code example in `main3_m60.sh` already works for 360 scenes. However that `tanks_and_temples` dataset also has a lot of `pose`, `intrinsics` and other data, which I'm not sure how to generate. 

1. Would you recommend `main3_m60.sh` as a better starting point instead for 360 scenes?
2. Also if I only have images, how to about generating the rest of the `pose`, `intrinsics` to make it work for 360 scenese?

**Comment by jeongyw12382** [comment]
Oh. Sure I could add it. 
I'm sorry for announcing it but I have an event that I should end up with until this week. 
So, can I add the scripts at the end of this week?

**Comment by jeongyw12382** [comment]
I'll close this issue after adding the utils about the "pose + intrinsic" calibration step using COLMAP.

**Comment by vishnukool** [comment]
Thanks @jeongyw12382, yes that would be great!

**Comment by jeongyw12382** [comment]
@vishnukool Sorry for being late. I have some work that I should conclude until this Wednesday but it is still in progress. Let me know your email so that I could inform you whenever I update the code.

**Comment by jeongyw12382** [comment]
I have just added colmap utils and updated the manual for usage. Could you check for it?

**Comment by jeongyw12382** [comment]
Closing the issue after adding the COLMAP utils. Please let me know if you have any trouble of using the COLMAP utils.
